// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpaxrnOvI0UxyMBaGOdO9C9DmPMpBUDjM',
    appId: '1:464336117304:web:4440c599a24015462350cd',
    messagingSenderId: '464336117304',
    projectId: 'attendence-app-f3f49',
    authDomain: 'attendence-app-f3f49.firebaseapp.com',
    storageBucket: 'attendence-app-f3f49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrCQ_K9NnYOm9oHP--j9bS8xqlF8aFiBg',
    appId: '1:464336117304:android:81350501635315642350cd',
    messagingSenderId: '464336117304',
    projectId: 'attendence-app-f3f49',
    storageBucket: 'attendence-app-f3f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlQJCX_5qEJ183xNtKPH1HYOwyKfWICmw',
    appId: '1:464336117304:ios:a24c1975d83a9c442350cd',
    messagingSenderId: '464336117304',
    projectId: 'attendence-app-f3f49',
    storageBucket: 'attendence-app-f3f49.appspot.com',
    iosClientId: '464336117304-101i1deu0pi47bkrppjuq9nn5v3d6uui.apps.googleusercontent.com',
    iosBundleId: 'co',
  );
}
